version: "3.8"

services:
  web:
    build: .

    restart: always
    
    volumes:
      - .:/app

    environment: 
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - MAIL_FROM=${MAIL_FROM}
      - DOMAIN=${DOMAIN}
      - REDIS_LOGOUT_URL=${REDIS_LOGOUT_URL}
      - REDIS_MQ_URL=${REDIS_MQ_URL}

    ports:
      - "8000:8000"

    depends_on:
      - redis

    networks:
      - app-network

  redis:
    image: redis

    restart: always

    ports:
     - "6379:6379"

    networks:
      - app-network
        # aliases:
        #   - redis

  worker:
    build: .

    restart: always

    command: sh worker.sh

    volumes:
      - .:/app

    depends_on:
      - redis

    environment:
      - REDIS_MQ_URL=${REDIS_MQ_URL}

    networks:
      - app-network
  
  nginx:
    image: nginx

    restart: always

    ports:
      - 80:80
      - 443:443
    
    volumes:
      - ./nginx/bookly.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/book-registration.ddns.net/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/book-registration.ddns.net/privkey.pem:/etc/ssl/private/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/nginx/ssl-dhparams.pem

    networks:
      - app-network

networks:
  app-network:
    driver: bridge