
x-common-config: &common-config

  build: 
    context: .
    dockerfile: Dockerfile
  
  image: ${IMAGE_NAME:-booktracker}:${IMAGE_TAG:-latest}

  pull_policy: build

  restart: always

  environment: 
    - DATABASE_URL=${DATABASE_URL}
    - JWT_SECRET=${JWT_SECRET}
    - JWT_ALGORITHM=${JWT_ALGORITHM}
    - MAIL_FROM=${MAIL_FROM}
    - REDIS_URL=${REDIS_URL}
    - MAIL_USERNAME=${MAIL_USERNAME}
    - MAIL_PASSWORD=${MAIL_PASSWORD}
    - MAIL_PORT=${MAIL_PORT}
    - MAIL_SERVER=${MAIL_SERVER}
    - MAIL_FROM_NAME=${MAIL_FROM_NAME}
    - DOMAIN=${DOMAIN}
    - APP_PORT=${APP_PORT}

  env_file:
    - ./.env
  
  depends_on:
    redis:
      condition: service_healthy

  networks:
    - app-network

services:
  web:
    <<: *common-config

    healthcheck:
      test: ["CMD", "bash", "./healthcheck.sh"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 20s

    
  redis:
    image: redis

    restart: always

    networks:
      - app-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s


  worker:
    <<: *common-config

    command: bash worker.sh
