version: "3.9"

services:
  nginx:
    image: nginx

    restart: always

    ports:
      - 80:80
      - 443:443
    
    volumes:
      - ./nginx/bookly.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/book-registration.ddns.net/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/book-registration.ddns.net/privkey.pem:/etc/ssl/private/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/nginx/ssl-dhparams.pem

    networks:
      - development
      - production


networks:
  development:
    external: true
  production:
    external: true